version: '3.7'
services: 
    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        env_file:
          - ./config/mysql.env
        ports: 
          - 3307:3307
        volumes: 
            - mysql_db_data:/var/lib/mysql
            
    adminer_container:
        image: adminer:latest
        environment: 
            ADMINER_DEFAULT_SERVER: mysql_db
            ADMINER_DESIGN: galkaev
        ports: 
          - 8080:8080
        

volumes: 
    mysql_db_data: 
    
